# Docker Compose override for development
# This file is automatically loaded alongside docker-compose.yml

version: '3.8'

services:
  ocr-api:
    environment:
      - DEBUG=true
    volumes:
      # Mount source code for development
      - .:/app
      - /app/__pycache__  # Exclude pycache
    ports:
      # Expose additional port for debugging
      - "8001:8000"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
